# Generated by Django 4.1.1 on 2023-08-06 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porta',
            name='registo_hora',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
