# Generated by Django 4.1.1 on 2023-08-07 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_porta_registo_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porta',
            name='registo_hora',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 7, 16, 13, 36, 803470)),
        ),
    ]
