# Generated by Django 4.1.1 on 2023-08-07 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_porta_registo_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='porta',
            name='registo_hora',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 7, 16, 17, 28, 136015)),
        ),
    ]
