# Generated by Django 4.1.1 on 2023-08-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_text_mensagem_texto_alter_porta_registo_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porta',
            name='registo_hora',
            field=models.DateTimeField(),
        ),
    ]
