name: CI/CD Python Django with Docker

on:
  push:
    branches:
      - main  # ou a branch que você quer acompanhar

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Use a versão de Python desejada

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r registration/requirements.txt  # Substitua pelo nome do arquivo de requisitos

    - name: Run Django Migrations
      run: |
        python manage.py migrate

    - name: Collect Static Files
      run: |
        python manage.py collectstatic --noinput

    - name: Build and Tag Docker Image
      run: |
        docker build -t thunderstorm710/n3e-porta:latest .
        docker tag thunderstorm710/n3e-porta:latest thunderstorm710/n3e-porta:latest

    - name: Login to Docker Hub
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Push Docker Image
      run: |
        docker push thunderstorm710/n3e-porta:latest
